import Foundation

struct TranscriptSegment: Identifiable, Hashable, Codable {
    var id = UUID()
    /// Raw speaker label as produced by SpeakerKit (e.g. "Speaker 1"). Stable across edits.
    let speakerLabel: String
    let text: String
    let start: TimeInterval
    let end: TimeInterval
}

struct ActionItem: Identifiable, Hashable, Codable {
    var id = UUID()
    /// Either a raw speaker label like "Speaker 1" (resolves through the recording's
    /// `displayName(for:)` so transcript renames flow into action items automatically),
    /// or a freeform name the model extracted, or "Unassigned".
    var assignee: String
    /// One-sentence description of what needs to be done.
    var task: String
    /// Freeform "when" — "Friday", "next Tuesday", "by end of quarter". Nil if not mentioned.
    var dueDate: String?
}

struct Recording: Identifiable, Hashable, Codable {
    let id: UUID
    /// Filename only (relative to the Recordings directory). Absolute paths are not stable
    /// across app installs on iOS, so we reconstruct the URL on demand.
    let audioFilename: String
    let createdAt: Date
    var duration: TimeInterval
    var segments: [TranscriptSegment] = []
    var summary: String?
    /// Short title (3-5 words) generated by the summarizer for use in lists and share output.
    var title: String?
    /// Concrete decisions reached during the conversation, one sentence each.
    var decisions: [String] = []
    /// Action items extracted by the meeting-extraction pass.
    var actionItems: [ActionItem] = []
    /// User-supplied display names mapped from raw speaker labels: ["Speaker 1": "Sarah"].
    var customSpeakerNames: [String: String] = [:]

    private enum CodingKeys: String, CodingKey {
        case id, audioFilename, createdAt, duration, segments, summary, title
        case decisions, actionItems, customSpeakerNames
    }

    init(
        id: UUID,
        audioFilename: String,
        createdAt: Date,
        duration: TimeInterval
    ) {
        self.id = id
        self.audioFilename = audioFilename
        self.createdAt = createdAt
        self.duration = duration
    }

    /// Backward-compatible decode — recordings saved before each new field was introduced
    /// can be loaded without their newer fields and default to empty.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        audioFilename = try c.decode(String.self, forKey: .audioFilename)
        createdAt = try c.decode(Date.self, forKey: .createdAt)
        duration = try c.decode(TimeInterval.self, forKey: .duration)
        segments = try c.decodeIfPresent([TranscriptSegment].self, forKey: .segments) ?? []
        summary = try c.decodeIfPresent(String.self, forKey: .summary)
        title = try c.decodeIfPresent(String.self, forKey: .title)
        decisions = try c.decodeIfPresent([String].self, forKey: .decisions) ?? []
        actionItems = try c.decodeIfPresent([ActionItem].self, forKey: .actionItems) ?? []
        customSpeakerNames = try c.decodeIfPresent([String: String].self, forKey: .customSpeakerNames) ?? [:]
    }

    func audioURL(in recordingsDir: URL) -> URL {
        recordingsDir.appendingPathComponent(audioFilename)
    }

    /// Display name for a speaker label, falling back to the raw label.
    func displayName(for speakerLabel: String) -> String {
        customSpeakerNames[speakerLabel] ?? speakerLabel
    }

    /// Distinct raw speaker labels in first-appearance order.
    var distinctSpeakerLabels: [String] {
        var seen = Set<String>()
        var ordered: [String] = []
        for seg in segments where seen.insert(seg.speakerLabel).inserted {
            ordered.append(seg.speakerLabel)
        }
        return ordered
    }

    /// Flat transcript text with display names (used for summarization / extraction input + share).
    var flatTranscript: String {
        segments.map { "\(displayName(for: $0.speakerLabel)): \($0.text)" }.joined(separator: "\n")
    }

    /// Lowercased blob used for substring search across the library.
    var searchableText: String {
        var parts: [String] = []
        if let title { parts.append(title) }
        if let summary { parts.append(summary) }
        parts.append(contentsOf: decisions)
        for item in actionItems {
            parts.append(item.assignee)
            parts.append(item.task)
            if let d = item.dueDate { parts.append(d) }
        }
        for seg in segments {
            parts.append(displayName(for: seg.speakerLabel))
            parts.append(seg.text)
        }
        return parts.joined(separator: " ").lowercased()
    }
}
